version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: docker/dev.node.Dockerfile
      # target: dev
      args:
        USERID: $DOCKER_USER_UID
        GROUPID: $DOCKER_USER_GID
    ports:
      - "${FRONTEND_HTTP_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app/:/var/www/app
    tty: true
    user: node
